spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource:
    url: jdbc:mysql://${DB}:3306/boot_db?useUnicode=true&charaterEncoding =utf-8&useSSL=false&serverTimezone=UTC&autoReconnection=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


DB: 127.0.0.1